models: https://utdallas.box.com/shared/static/con44iqej33weg9f3rpxof61eh3x2x21.zip
calibration: https://utdallas.box.com/shared/static/nlp4c6vtd0n8o0entxlh1vxdpcdeh0h8.zip
subject_1: https://utdallas.box.com/shared/static/w0voy9bixtxyclo52841xyamock2lxpt.zip
subject_2: https://utdallas.box.com/shared/static/j498kxxrkvaf674tvmt4su4ad0bz9s9f.zip
subject_3: https://utdallas.box.com/shared/static/shklq33yaoozh9gm681nxwnq0o3y0y1d.zip
subject_4: https://utdallas.box.com/shared/static/dew68k7b3ya09t40818gpfxm95oa4yeq.zip
subject_5: https://utdallas.box.com/shared/static/mutor2a09kudze1yw173gsfetsru7ces.zip
subject_6: https://utdallas.box.com/shared/static/iyja7rdbjx2ksgjhmdu6mx3zqvaurdni.zip
subject_7: https://utdallas.box.com/shared/static/4g5qyig6i4uz1rgrzkcu9n4mhdjs74m2.zip
subject_8: https://utdallas.box.com/shared/static/khrb5guy8rdwnoqi4euk2w0mk5lslxkn.zip
subject_9: https://utdallas.box.com/shared/static/3x5yitydmbmwolq9bty5dd2udu5v52fc.zip
poses: https://utdallas.box.com/shared/static/2lofbp2yd005d8o213ns77mdrtxg8eep.zip
